#!/bin/bash 
./asm < $1.asm > $1.mips 2>tests/error.txt
echo "---------------------------------------------------------------------"
echo "INPUT"
echo $(cat $1.asm)
echo "OUTPUT:"
echo $(xxd $1.mips)
echo "STDERR:"
echo $(cat tests/error.txt)
echo "---------------------------------------------------------------------"
